---
title: "project1"
output: pdf_document
---

```{r setup, include=FALSE}
setwd("###/Downloads/household_power_consumption")
```

```{r message=FALSE, warning=FALSE}
if(!require(tidyverse)) install.packages("tidyverse")
library(tidyverse)
if(!require(purrr)) install.packages("purrr")
library(purrr)

```


```{r}
fname=dir(pattern = "txt$")
data_raw=read.table(fname,header = TRUE, sep = ";",na.strings="?")

data=data_raw %>% 
  mutate(Date=as.Date(Date,"%d/%m/%Y")) %>% 
  filter(Date>="2007-02-01" & Date<="2007-02-02")
```

## Plot 1
```{r}
plot1=function(){
  hist(data$Global_active_power, main="Global Active Power",
     xlab="Global Active Power (kilowatts)", ylab="Frequency",col="red")}
plot1()

png("plot1.png", width=480, height=480)
plot1()
dev.off()
```
## Plot 2
```{r}
data=data%>%mutate(datetime=paste(Date,Time)%>%as.POSIXct(format="%Y-%m-%d %H:%M:%S"))
plot2=function(){
  plot(data$datetime, data$Global_active_power,type="l",
     xlab="",ylab="Global Active Power (kilowatts)")}
plot2()

png("plot2.png", width=480, height=480)
plot2()
dev.off()
```
## Plot 3
```{r}
plot3=function(){
plot(data$datetime,data$Sub_metering_1,type="l",
     xlab="",ylab="Energy sub metering")
lines(data$datetime,data$Sub_metering_2,col=2)
lines(data$datetime,data$Sub_metering_3,col=4)
legend("topright",col = c(1,2,4),lty=c(1,1,1),
       legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))}

plot3()
png("plot3.png", width=480, height=480)
plot3()
dev.off()
```

## Plot 4
```{r}
plot4=function(){
  plot(data$datetime,data$Global_reactive_power,type="l",
     xlab="datetime",ylab="Global_reactive_power")
}

plot4()
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
for(i in 1:4)  get(paste0("plot",i))()
dev.off()
```
